In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,VotingClassifier,StackingClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [2]:
df = pd.read_csv("C:/Users/gpro0/OneDrive/Рабочий стол/Data Science course/employee_promotion.csv")
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                  8           0                49.0            0  
1                  4           0                60.0            0  
2                  7           0                50.0            0  
3                 10           0                50.0            0  
4                  2           0                73.0            0

In [3]:
df.isna().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             52399 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  awards_won            54808 non-null  int64  
 11  avg_training_score    52248 non-null  float64
 12  is_promoted           54808 non-null  int64  
dtypes: float64(2), int64(6), object(5)
memory usage: 5.4+ MB


In [5]:
for i in df.select_dtypes(['object']).columns:
    df[i] = df[i].fillna(df[i].mode()[0])
df.isna().sum()

employee_id                0
department                 0
region                     0
education                  0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64

In [6]:
for i in df.select_dtypes(include=['float']).columns:
    df[i]=df[i].fillna(df[i].mean())
df.isna().sum()


employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
awards_won              0
avg_training_score      0
is_promoted             0
dtype: int64

In [7]:
df.drop("employee_id", axis=1, inplace=True)
df.head()

department     region         education gender recruitment_channel  \
0  Sales & Marketing   region_7  Master's & above      f            sourcing   
1         Operations  region_22        Bachelor's      m               other   
2  Sales & Marketing  region_19        Bachelor's      m            sourcing   
3  Sales & Marketing  region_23        Bachelor's      m               other   
4         Technology  region_26        Bachelor's      m               other   

   no_of_trainings  age  previous_year_rating  length_of_service  awards_won  \
0                1   35                   5.0                  8           0   
1                1   30                   5.0                  4           0   
2                1   34                   3.0                  7           0   
3                2   39                   1.0                 10           0   
4                1   45                   3.0                  2           0   

   avg_training_score  is_promoted  
0                49.0            0  
1                60.0            0  
2                50.0            0  
3                50.0            0  
4                73.0            0

In [8]:
col = df.select_dtypes(['object']).columns
le=LabelEncoder()
for i in col:
    df[i]=le.fit_transform(df[i])
df.head()

department  region  education  gender  recruitment_channel  \
0           7      31          2       0                    2   
1           4      14          0       1                    0   
2           7      10          0       1                    2   
3           7      15          0       1                    0   
4           8      18          0       1                    0   

   no_of_trainings  age  previous_year_rating  length_of_service  awards_won  \
0                1   35                   5.0                  8           0   
1                1   30                   5.0                  4           0   
2                1   34                   3.0                  7           0   
3                2   39                   1.0                 10           0   
4                1   45                   3.0                  2           0   

   avg_training_score  is_promoted  
0                49.0            0  
1                60.0            0  
2                50.0            0  
3                50.0            0  
4                73.0            0

In [9]:
x=df.drop('is_promoted',axis=1)
y=df.is_promoted

In [39]:
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.2)

In [45]:
rf=RandomForestClassifier(n_estimators=27, criterion="log_loss")
model=rf.fit(trainx,trainy)
pred=model.predict(testx)

print(accuracy_score(testy,pred))
print(confusion_matrix(testy,pred))

0.929757343550447
[[9916   84]
 [ 686  276]]


In [41]:
dt=DecisionTreeClassifier(max_depth=150, criterion="log_loss")
lr=LogisticRegression()
knn=KNeighborsClassifier(n_neighbors=21, n_jobs=-1)
nb=GaussianNB()
estimators=[('DT',dt),('LR',lr),('RF',lr),('KNN',knn),('NB',nb)]
vt=VotingClassifier(estimators, flatten_transform= True)
st = StackingClassifier(estimators)


In [42]:
for i in [lr, dt, nb, knn, vt, rf, st]:
    model = i.fit(trainx, trainy)
    pred = model.predict(testx)
    print(f"{str(i)}\n,{confusion_matrix(testy, pred)}\n,{accuracy_score(testy, pred)}\n-----------")

c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()
,[[9929   71]
 [ 862  100]]
,0.914887794198139
-----------
DecisionTreeClassifier(criterion='log_loss', max_depth=150)
,[[9303  697]
 [ 565  397]]
,0.8848750228060573
-----------
GaussianNB()
,[[9855  145]
 [ 838  124]]
,0.9103265827403758
-----------
KNeighborsClassifier(n_jobs=-1, n_neighbors=21)
,[[9991    9]
 [ 848  114]]
,0.921820835613939
-----------


c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(criterion='log_loss',
                                                     max_depth=150)),
                             ('LR', LogisticRegression()),
                             ('RF', LogisticRegression()),
                             ('KNN',
                              KNeighborsClassifier(n_jobs=-1, n_neighbors=21)),
                             ('NB', GaussianNB())])
,[[9929   71]
 [ 859  103]]
,0.9151614668856048
-----------
RandomForestClassifier(criterion='log_loss', n_estimators=27)
,[[9922   78]
 [ 695  267]]
,0.9294836708629812
-----------


c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

StackingClassifier(estimators=[('DT',
                                DecisionTreeClassifier(criterion='log_loss',
                                                       max_depth=150)),
                               ('LR', LogisticRegression()),
                               ('RF', LogisticRegression()),
                               ('KNN',
                                KNeighborsClassifier(n_jobs=-1,
                                                     n_neighbors=21)),
                               ('NB', GaussianNB())])
,[[9943   57]
 [ 756  206]]
,0.9258347016967706
-----------


In [43]:
ab = AdaBoostClassifier()
model_ab=ab.fit(trainx,trainy)
pred_ab=model_ab.predict(testx)

print(accuracy_score(testy,pred_ab))
print(confusion_matrix(testy,pred_ab))

c:\Users\gpro0\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


0.9247400109469075
[[9974   26]
 [ 799  163]]


In [44]:
gb = GradientBoostingClassifier()
model_gb=gb.fit(trainx,trainy)
pred_gb=model_gb.predict(testx)

print(accuracy_score(testy,pred_gb))
print(confusion_matrix(testy,pred_gb))

0.9337712096332786
[[9982   18]
 [ 708  254]]
